[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies.anyhow]
version = "1"
[dependencies.tokio]
version = "1"
features = ["full", "parking_lot"]
[dependencies.clap]
version = "4"
[dependencies.ws_client]
path = "../ws_client"
[dependencies.utils]
path = "../utils"