[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies.log]
version = "0.4"
[dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter", "json", "parking_lot", "tracing-log"]
[dependencies.tracing]
version = "0.1.40"
features = ["log", "attributes"]