---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Ship files to server
      synchronize:
        src: ../gui/dist/
        dest: '{{app_root}}'
        recursive: yes
        delete: yes

    - name: Ship service file to server
      template:
        src: "pvtop.service.j2"
        dest: "/etc/systemd/system/pvtop.service"
        mode: 0755

    - name: Configuring service
      service:
        name: pvtop
        state: restarted
        enabled: true