---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Ship files to server
      synchronize:
        src: ../ctop
        dest: '{{app_root}}/ctop'
        recursive: yes
        delete: yes

    - name: Ship event subscription service file to server
      template:
        src: "ctop_event_subscription.service.j2"
        dest: "/etc/systemd/system/ctop_event_subscription.service"
        mode: 0755

    - name: Ship redis event stream service file to server
      template:
        src: "ctop_redis_event_stream.service.j2"
        dest: "/etc/systemd/system/ctop_redis_event_stream.service"
        mode: 0755

    - name: init database
      command: '{{app_root}}/ctop db --db.url {{postgres_url}} init'
    
    - name: migrate database
      command: '{{app_root}}/ctop db --db.url {{postgres_url}} migrate'

    - name: Configuring event subscription service
      service:
        name: ctop_event_subscription
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Configuring redis event stream service
      service:
        name: ctop_redis_event_stream
        state: restarted
        enabled: true
        daemon_reload: true